# This is a basic workflow to help you get started with Actions

name: macOS_install_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          brew install gnu-which
          curl "https://raw.githubusercontent.com/Crilum/update-app-script/main/install-macos" | sudo bash
          echo "Here is where Update is:"
          which update
          /usr/local/bin/update help
          update
