# This is a basic workflow to help you get started with Actions

name: macOS_install_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Install Update
        run: brew install gnu-which
        run: curl "https://raw.githubusercontent.com/Crilum/update-app-script/main/install-macos" | sudo bash
        run: echo "Here is where Update is:"
        run: gwhich update
      - name: Test Update
        run: update help
        run: update homebrew
