# This is a basic workflow to help you get started with Actions

name: Test_Update_Install

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test_Update_Install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Update
        run: |
          curl "https://raw.githubusercontent.com/Crilum/update-app-script/main/install" | sudo bash
          echo "Here is where Update is:"
          which update
      - name: Test Update
        run: |
          /usr/local/bin/update help
          update
