# This is a basic workflow to help you get started with Actions

name: Test-on-RPi

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test-install-on-RPi:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, ARM64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Install Update
        run: |
          curl "https://raw.githubusercontent.com/Crilum/update-app-script/main/install" | sudo bash
          echo "Here is where Update is:"
          which update
      - name: Test Update
        run: |
          update help
          update
          
